### PR TITLE
feat: configurable external fga server

### PR DESCRIPTION
**Pull request by le-yams**
Add inputs so an external server can be used to perform the tests

## Description

To be able to run the tests against a specific OpenFGA version, we have to use an external server instead of the cli built-in one.
The PR adds two optional inputs so the user can specify a server url and its token.
If the server url is not specified, the cli built-in server is used (current behavior)

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by le-yams** [comment]
To be done: adding an example and a test in the workflow

**Comment by le-yams** [comment]
I added the job `test_conditions_support` in the test workflow which verifies that the action actually runs the tests against the specified server

**Review by rhamzeh — APPROVED** [review]

**Comment by rhamzeh** [comment]
Thanks @le-yams! This is useful! Merging it. Hopefully some of the logic here can be dropped in a future iteration once we add the relevant flag in the CLI

Relevant conversation: https://github.com/openfga/cli/issues/335

**Comment by yann-disanto** [comment]
> Thanks @le-yams! This is useful! Merging it. 

Thank you 😃 

>Hopefully some of the logic here can be dropped in a future iteration once we add the relevant flag in the CLI
> 
> Relevant conversation: [openfga/cli#335](https://github.com/openfga/cli/issues/335)

Awesome!

**Pull request merged**
